"""Deterministic disposable MP4 fixture for Boost qualification.

The bytes are an offline-generated 3-second black H.264/MP4 clip (360x640,
24fps, no audio). It contains no user/client data and requires no ffmpeg at
runtime. This exists only so the authorized publish pipeline can be qualified
on a machine without media-generation tooling installed.
"""
from __future__ import annotations

import base64
import hashlib
from pathlib import Path

FIXTURE_SHA256 = "7a4b13dad13016562f74845f28f3ae2a92663dc59e03c428dc29d7b9b761ac07"
FIXTURE_SIZE = 3897
_FIXTURE_B64 = (
    "AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAAAaRbW9vdgAAAGxtdmhkAAAAAAAAAAAAAAAAAAAD6AAAC7gAAQAA"
    "AQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAgAABbx0cmFrAAAAXHRraGQAAAADAAAAAAAAAAAAAAABAAAAAAAAC7gAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAA"
    "AAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAWgAAAKAAAAAAAAkZWR0cwAAABxlbHN0AAAAAAAAAAEAAAu4AAAEAAABAAAAAAU0"
    "bWRpYQAAACBtZGhkAAAAAAAAAAAAAAAAAAAwAAAAkABVxAAAAAAALWhkbHIAAAAAAAAAAHZpZGUAAAAAAAAAAAAAAABWaWRl"
    "b0hhbmRsZXIAAAAE321pbmYAAAAUdm1oZAAAAAEAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAA"
    "AQAABJ9zdGJsAAAAv3N0c2QAAAAAAAAAAQAAAK9hdmMxAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAWgCgABIAAAASAAAAAAA"
    "AAABFUxhdmM2MS4xOS4xMDEgbGlieDI2NAAAAAAAAAAAAAAAGP//AAAANWF2Y0MBZAAe/+EAGmdkAB6s2UFwUeXwEQAAAwAB"
    "AAADADAPFi2WAQAEaO+Py/34+AAAAAAQcGFzcAAAAAEAAAABAAAAFGJ0cnQAAAAAAAAWlQAAAAAAAAAYc3R0cwAAAAAAAAAB"
    "AAAASAAAAgAAAAAUc3RzcwAAAAAAAAABAAAAAQAAAkhjdHRzAAAAAAAAAEcAAAABAAAEAAAAAAEAAAoAAAAAAQAABAAAAAAB"
    "AAAAAAAAAAEAAAIAAAAAAQAACgAAAAABAAAEAAAAAAEAAAAAAAAAAQAAAgAAAAABAAAKAAAAAAEAAAQAAAAAAQAAAAAAAAAB"
    "AAACAAAAAAEAAAoAAAAAAQAABAAAAAABAAAAAAAAAAEAAAIAAAAAAQAACgAAAAABAAAEAAAAAAEAAAAAAAAAAQAAAgAAAAAB"
    "AAAKAAAAAAEAAAQAAAAAAQAAAAAAAAABAAACAAAAAAEAAAoAAAAAAQAABAAAAAABAAAAAAAAAAEAAAIAAAAAAQAACgAAAAAB"
    "AAAEAAAAAAEAAAAAAAAAAQAAAgAAAAABAAAKAAAAAAEAAAQAAAAAAQAAAAAAAAABAAACAAAAAAEAAAoAAAAAAQAABAAAAAAB"
    "AAAAAAAAAAEAAAIAAAAAAQAACgAAAAABAAAEAAAAAAEAAAAAAAAAAQAAAgAAAAABAAAKAAAAAAEAAAQAAAAAAQAAAAAAAAAB"
    "AAACAAAAAAEAAAoAAAAAAQAABAAAAAABAAAAAAAAAAEAAAIAAAAAAQAACgAAAAABAAAEAAAAAAEAAAAAAAAAAQAAAgAAAAAB"
    "AAAKAAAAAAEAAAQAAAAAAQAAAAAAAAABAAACAAAAAAEAAAoAAAAAAQAABAAAAAABAAAAAAAAAAEAAAIAAAAAAQAACgAAAAAB"
    "AAAEAAAAAAEAAAAAAAAAAQAAAgAAAAABAAAIAAAAAAIAAAIAAAAAHHN0c2MAAAAAAAAAAQAAAAEAAABIAAAAAQAAATRzdHN6"
    "AAAAAAAAAAAAAABIAAADEwAAABUAAAASAAAAEgAAABIAAAAWAAAAFAAAABIAAAASAAAAFgAAABQAAAASAAAAEgAAABYAAAAU"
    "AAAAEgAAABIAAAAWAAAAFAAAABIAAAASAAAAFgAAABQAAAASAAAAEgAAABYAAAAUAAAAEgAAABIAAAAWAAAAFAAAABIAAAAS"
    "AAAAFgAAABQAAAASAAAAEgAAABYAAAAUAAAAEgAAABIAAAAWAAAAFAAAABIAAAASAAAAFgAAABQAAAASAAAAEgAAABYAAAAU"
    "AAAAEgAAABIAAAAWAAAAFAAAABIAAAASAAAAFgAAABQAAAASAAAAEgAAABYAAAAUAAAAEgAAABIAAAAVAAAAFAAAABIAAAAS"
    "AAAAFQAAABQAAAASAAAAFHN0Y28AAAAAAAAAAQAABsEAAABhdWR0YQAAAFltZXRhAAAAAAAAACFoZGxyAAAAAAAAAABtZGly"
    "YXBwbAAAAAAAAAAAAAAAACxpbHN0AAAAJKl0b28AAAAcZGF0YQAAAAEAAAAATGF2ZjYxLjcuMTAzAAAACGZyZWUAAAiAbWRh"
    "dAAAAq0GBf//qdxF6b3m2Ui3lizYINkj7u94MjY0IC0gY29yZSAxNjQgcjMxMDggMzFlMTlmOSAtIEguMjY0L01QRUctNCBB"
    "VkMgY29kZWMgLSBDb3B5bGVmdCAyMDAzLTIwMjMgLSBodHRwOi8vd3d3LnZpZGVvbGFuLm9yZy94MjY0Lmh0bWwgLSBvcHRp"
    "b25zOiBjYWJhYz0xIHJlZj0xIGRlYmxvY2s9MTowOjAgYW5hbHlzZT0weDM6MHgxMTMgbWU9aGV4IHN1Ym1lPTIgcHN5PTEg"
    "cHN5X3JkPTEuMDA6MC4wMCBtaXhlZF9yZWY9MCBtZV9yYW5nZT0xNiBjaHJvbWFfbWU9MSB0cmVsbGlzPTAgOHg4ZGN0PTEg"
    "Y3FtPTAgZGVhZHpvbmU9MjEsMTEgZmFzdF9wc2tpcD0xIGNocm9tYV9xcF9vZmZzZXQ9MCB0aHJlYWRzPTcgbG9va2FoZWFk"
    "X3RocmVhZHM9MiBzbGljZWRfdGhyZWFkcz0wIG5yPTAgZGVjaW1hdGU9MSBpbnRlcmxhY2VkPTAgYmx1cmF5X2NvbXBhdD0w"
    "IGNvbnN0cmFpbmVkX2ludHJhPTAgYmZyYW1lcz0zIGJfcHlyYW1pZD0yIGJfYWRhcHQ9MSBiX2JpYXM9MCBkaXJlY3Q9MSB3"
    "ZWlnaHRiPTEgb3Blbl9nb3A9MCB3ZWlnaHRwPTEga2V5aW50PTI1MCBrZXlpbnRfbWluPTI0IHNjZW5lY3V0PTQwIGludHJh"
    "X3JlZnJlc2g9MCByY19sb29rYWhlYWQ9MTAgcmM9Y3JmIG1idHJlZT0xIGNyZj0yMy4wIHFjb21wPTAuNjAgcXBtaW49MCBx"
    "cG1heD02OSBxcHN0ZXA9NCBpcF9yYXRpbz0xLjQwIGFxPTE6MS4wMACAAAAAXmWIhAA7/9n8D4H6QU/ecZ/3u4XVBZIczzX8"
    "sKn1YNUY9AAAAwAHuCYuxsiqF2nxZAAfwAAhI7aCJGkc4LcqOcAAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMANaEAAAAR"
    "QZokGIb//qeEAAADAAADAccAAAAOQZ5CQhf/AAADAAADAQ8AAAAOAZ5hRCv/AAADAAADAXcAAAAOAZ5jRCv/AAADAAADAXcA"
    "AAASQZpoNExDf/6nhAAAAwAAAwHHAAAAEEGehkURLC//AAADAAADAQ8AAAAOAZ6lRCv/AAADAAADAXcAAAAOAZ6nRCv/AAAD"
    "AAADAXcAAAASQZqsNExDf/6nhAAAAwAAAwHHAAAAEEGeykUVLC//AAADAAADAQ8AAAAOAZ7pRCv/AAADAAADAXcAAAAOAZ7r"
    "RCv/AAADAAADAXcAAAASQZrwNExDf/6nhAAAAwAAAwHHAAAAEEGfDkUVLC//AAADAAADAQ8AAAAOAZ8tRCv/AAADAAADAXcA"
    "AAAOAZ8vRCv/AAADAAADAXcAAAASQZs0NExDf/6nhAAAAwAAAwHHAAAAEEGfUkUVLC//AAADAAADAQ8AAAAOAZ9xRCv/AAAD"
    "AAADAXcAAAAOAZ9zRCv/AAADAAADAXcAAAASQZt4NExDf/6nhAAAAwAAAwHHAAAAEEGflkUVLC//AAADAAADAQ8AAAAOAZ+1"
    "RCv/AAADAAADAXcAAAAOAZ+3RCv/AAADAAADAXcAAAASQZu8NExDf/6nhAAAAwAAAwHHAAAAEEGf2kUVLC//AAADAAADAQ8A"
    "AAAOAZ/5RCv/AAADAAADAXcAAAAOAZ/7RCv/AAADAAADAXcAAAASQZvgNExDf/6nhAAAAwAAAwHHAAAAEEGeHkUVLC//AAAD"
    "AAADAQ8AAAAOAZ49RCv/AAADAAADAXcAAAAOAZ4/RCv/AAADAAADAXcAAAASQZokNExDf/6nhAAAAwAAAwHHAAAAEEGeQkUV"
    "LC//AAADAAADAQ8AAAAOAZ5hRCv/AAADAAADAXcAAAAOAZ5jRCv/AAADAAADAXcAAAASQZpoNExDf/6nhAAAAwAAAwHHAAAA"
    "EEGehkUVLC//AAADAAADAQ8AAAAOAZ6lRCv/AAADAAADAXcAAAAOAZ6nRCv/AAADAAADAXcAAAASQZqsNExDf/6nhAAAAwAA"
    "AwHHAAAAEEGeykUVLC//AAADAAADAQ8AAAAOAZ7pRCv/AAADAAADAXcAAAAOAZ7rRCv/AAADAAADAXcAAAASQZrwNExDf/6n"
    "hAAAAwAAAwHHAAAAEEGfDkUVLC//AAADAAADAQ8AAAAOAZ8tRCv/AAADAAADAXcAAAAOAZ8vRCv/AAADAAADAXcAAAASQZs0"
    "NExDf/6nhAAAAwAAAwHHAAAAEEGfUkUVLC//AAADAAADAQ8AAAAOAZ9xRCv/AAADAAADAXcAAAAOAZ9zRCv/AAADAAADAXcA"
    "AAASQZt4NExDf/6nhAAAAwAAAwHHAAAAEEGflkUVLC//AAADAAADAQ8AAAAOAZ+1RCv/AAADAAADAXcAAAAOAZ+3RCv/AAAD"
    "AAADAXcAAAASQZu8NExDf/6nhAAAAwAAAwHHAAAAEEGf2kUVLC//AAADAAADAQ8AAAAOAZ/5RCv/AAADAAADAXcAAAAOAZ/7"
    "RCv/AAADAAADAXcAAAASQZvgNExDf/6nhAAAAwAAAwHHAAAAEEGeHkUVLC//AAADAAADAQ8AAAAOAZ49RCv/AAADAAADAXcA"
    "AAAOAZ4/RCv/AAADAAADAXcAAAARQZokNExDP/6eEAAAAwAABvQAAAAQQZ5CRRUsL/8AAAMAAAMBDwAAAA4BnmFEK/8AAAMA"
    "AAMBdwAAAA4BnmNEK/8AAAMAAAMBdwAAABFBmmc0TEK//jhAAAADAAAbMQAAABBBnoVFFSwr/wAAAwAAAwF3AAAADgGepkQr"
    "/wAAAwAAAwF3"
)


def fixture_bytes() -> bytes:
    data = base64.b64decode(_FIXTURE_B64)
    if len(data) != FIXTURE_SIZE or hashlib.sha256(data).hexdigest() != FIXTURE_SHA256:
        raise RuntimeError("embedded Boost fixture integrity check failed")
    return data


def write_fixture(path: str | Path, *, overwrite: bool = False) -> Path:
    target = Path(path)
    if target.exists() and not overwrite:
        raise FileExistsError(f"refusing to overwrite existing file: {target}")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(fixture_bytes())
    return target
